-- * 테이블 생성 및 더미 데이터 세팅(주석 확인하며, 추가!)

-- 멤버 테이블 DROP & CREATE
DROP TABLE TB_MEMBER;

CREATE TABLE TB_MEMBER (
	USER_NO	NUMBER		NOT NULL,
	USER_ID	VARCHAR2(20)	UNIQUE	NOT NULL,
	USER_PW	VARCHAR2(20)		NOT NULL,
	USER_NAME	VARCHAR2(15)		NOT NULL,
	USER_FAILKEY	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_MEMBER"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "TB_MEMBER"."USER_ID" IS '유저 아이디';

COMMENT ON COLUMN "TB_MEMBER"."USER_PW" IS '유저비밀번호';

COMMENT ON COLUMN "TB_MEMBER"."USER_NAME" IS '유저이름';

COMMENT ON COLUMN "TB_MEMBER"."USER_FAILKEY" IS '로그인 실패횟수';

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"USER_NO");
    
-- 단어 테이블 DROP & CREATE    
DROP TABLE TB_WORD;
CREATE TABLE TB_WORD (
	USER_NO	NUMBER	REFERENCES TB_MEMBER(USER_NO) NOT NULL ,
	WORD_ENG	VARCHAR2(20)		NOT NULL,
	WORD_KOR	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN TB_WORD.USER_NO IS '회원번호';

COMMENT ON COLUMN TB_WORD.WORD_ENG IS '영어단어';

COMMENT ON COLUMN TB_WORD.WORD_KOR IS '한글단어';

-- 게시한 단어장 테이블 DROP & CREATE  
DROP TABLE TB_WORDLIST;
CREATE TABLE TB_WORDLIST (
	WORDLIST_TITLE	VARCHAR2(20)		NULL,
	WORDLIST_USER	VARCHAR(20)		NULL,
    WORDLIST_ENG VARCHAR(20)  NOT NULL,
    WORDLIST_KOR VARCHAR(20)  NOT NULL,
    USER_NO NUMBER REFERENCES TB_MEMBER(USER_NO) NOT NULL
);


COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_TITLE" IS '단어장이름';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_USER" IS '작성자';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_ENG" IS '리스트 영어단어';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_KOR" IS '리스트 한글단어';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_KOR" IS '식별용 유저넘버';

-- 퀴즈 기록 테이블 DROP & CREATE  

DROP TABLE TB_QUIZ;

CREATE TABLE TB_QUIZ(
    QUIZ_NO NUMBER PRIMARY KEY,
    QUIZ_POINT NUMBER NULL,
    QUIZ_TIME VARCHAR2(15) NULL,
    QUIZ_TITLE VARCHAR2(20) NOT NULL,
    QUIZ_USER_NO NUMBER NOT NULL
    );
    
COMMENT ON COLUMN "TB_QUIZ"."QUIZ_NO" IS '퀴즈 기록 고유 넘버';
COMMENT ON COLUMN "TB_QUIZ"."QUIZ_POINT" IS '퀴즈 점수';
COMMENT ON COLUMN "TB_QUIZ"."QUIZ_TIME" IS '퀴즈 풀이 시간';
COMMENT ON COLUMN "TB_QUIZ"."QUIZ_TITLE" IS '퀴즈 이름';
COMMENT ON COLUMN "TB_QUIZ"."QUIZ_TITLE" IS '식별용 유저넘버';


-- 필요한 시퀀스들 DROP & CREATE
DROP SEQUENCE SEQ_USERNO;

CREATE SEQUENCE SEQ_USERNO
NOCACHE;

DROP SEQUENCE SEQ_WORDLISTNO;

CREATE SEQUENCE SEQ_WORDLISTNO
NOCACHE;

DROP SEQUENCE SEQ_QUIZNO;

CREATE SEQUENCE SEQ_QUIZNO
NOCACHE;





-- 더미 데이터 삽입 (멤버 2명 / 멤버1 : 단어 10개 / 멤버2 : 단어 5개)
-- ㄴ 퀴즈와 워드리스트는 삽입되지 않으므로 프로그램 구동하여 테스트 겸 삽입 진행
-- 혹여, 오류 발생 시 더미 단어 추가할때 TB_MEMBER에서 USER_NO 확인하여 맞춰줘야함

INSERT INTO TB_MEMBER VALUES(SEQ_USERNO.NEXTVAL,'Admin','AD1234','관리자',0);
INSERT INTO TB_MEMBER VALUES(SEQ_USERNO.NEXTVAL,'First','PWPW','김첫째',0);

INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Dog','개');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Cat','고양이');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Mouse','쥐');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Horse','말');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Rabbit','토끼');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Cow','소');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Tiger','호랑이');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Pig','돼지');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Snake','뱀');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(1,'Camel','낙타');

INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(2,'Fire','불');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(2,'Water','물');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(2,'Window','창문');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(2,'Candy','사탕');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(2,'Food','음식');

commit;

