DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(20) UNIQUE,
    USERPW VARCHAR2(20),
    USERNAME VARCHAR2(15),
    FAILKEY NUMBER
    
);

DROP TABLE WORD;

CREATE TABLE WORD(
    USERID VARCHAR2(20) REFERENCES MEMBER(USERID),
    KOR VARCHAR2(20),
    ENG VARCHAR2(20)
    
);










-- 사용자 단어장 전체보기
SELECT KOR, ENG
FROM MEMBER
JOIN WORD USING (USERID)
WHERE USERID = 'Admin';

DROP TABLE TB_MEMBER;
DROP TABLE TB_WORD;
DROP TABLE TB_WORDLIST;




CREATE TABLE TB_MEMBER (
	USER_NO	NUMBER		NOT NULL,
	USER_ID	VARCHAR2(20)	UNIQUE	NOT NULL,
	USER_PW	VARCHAR2(20)		NOT NULL,
	USER_NAME	VARCHAR2(15)		NOT NULL,
	USER_FAILKEY	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_MEMBER"."USER_NO" IS '회원번호';

COMMENT ON COLUMN "TB_MEMBER"."USER_ID" IS '유저 아이디';

COMMENT ON COLUMN "TB_MEMBER"."USER_PW" IS '유저비밀번호';

COMMENT ON COLUMN "TB_MEMBER"."USER_NAME" IS '유저이름';

COMMENT ON COLUMN "TB_MEMBER"."USER_FAILKEY" IS '로그인 실패횟수';

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
	"USER_NO");

CREATE TABLE TB_WORD (
	USER_NO	NUMBER	REFERENCES TB_MEMBER(USER_NO) NOT NULL ,
	WORD_ENG	VARCHAR2(20)		NOT NULL,
	WORD_KOR	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN TB_WORD.USER_NO IS '회원번호';

COMMENT ON COLUMN TB_WORD.WORD_ENG IS '영어단어';

COMMENT ON COLUMN TB_WORD.WORD_KOR IS '한글단어';

CREATE TABLE TB_WORDLIST (
	WORDLIST_TITLE	VARCHAR2(20)		NULL,
	WORDLIST_USER	VARCHAR(20)		NULL,
    WORDLIST_ENG VARCHAR(20)  NOT NULL,
    WORDLIST_KOR VARCHAR(20)  NOT NULL,
    USER_NO NUMBER REFERENCES TB_MEMBER(USER_NO) NOT NULL
);

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_NO" IS '단어장번호';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_TITLE" IS '단어장이름';

COMMENT ON COLUMN "TB_WORDLIST"."WORDLIST_USER" IS '작성자';

DROP TABLE TB_QUIZ;

CREATE TABLE TB_QUIZ(
    QUIZ_NO NUMBER PRIMARY KEY,
    QUIZ_POINT NUMBER NULL,
    QUIZ_TIME VARCHAR2(15) NULL,
    QUIZ_TITLE VARCHAR2(20) NOT NULL,
    QUIZ_USER_NO NUMBER NOT NULL
    );


INSERT INTO TB_QUIZ VALUES(SEQ_QUIZNO.NEXTVAL,?,?,?,?);
UPDATE TB_QUIZ SET QUIZ_POINT = 80, QUIZ_ENDDATE = SYSDATE WHERE QUIZ_NO = 4;

SELECT QUIZ_ENDDATE - QUIZ_STARTDATE
FROM TB_QUIZ
WHERE QUIZ_NO = 4;


ROLLBACK;

DROP SEQUENCE SEQ_USERNO;

CREATE SEQUENCE SEQ_USERNO
NOCACHE;


DROP SEQUENCE SEQ_WORDLISTNO;

CREATE SEQUENCE SEQ_WORDLISTNO
NOCACHE;

DROP SEQUENCE SEQ_QUIZNO;

CREATE SEQUENCE SEQ_QUIZNO
NOCACHE;

INSERT INTO TB_WORDLIST VALUES(?,?,?,?,?);

INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'wa','와');

INSERT INTO TB_MEMBER VALUES(SEQ_USERNO.NEXTVAL,'Admin','AD1234','관리자',0);
INSERT INTO TB_MEMBER VALUES(SEQ_USERNO.NEXTVAL,'First','PWPW','김첫째',0);

INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Dog','개');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Cat','고양이');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Mouse','쥐');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Horse','말');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Rabbit','토끼');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Cow','소');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Tiger','호랑이');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Pig','돼지');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Snake','뱀');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(9,'Camel','낙타');

INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(10,'Fire','불');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(10,'Water','물');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(10,'Window','창문');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(10,'Candy','사탕');
INSERT INTO TB_WORD(USER_NO,WORD_ENG,WORD_KOR) VALUES(10,'Food','음식');

commit;

